name:                aoc2020
version:             0.1.0.0
github:              "emiflake/Advent-of-Code-2020"
license:             BSD3
author:              "Emily Martins"
maintainer:          "emily.flakeheart@gmail.com"
copyright:           "2020 Emily Martins"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/emiflake/Advent-of-Code-2020#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- containers
- mtl
- transformers
- text
- lens
- optparse-applicative
- exceptions
- prettyprinter == 1.7.*
- prettyprinter-ansi-terminal
- parser-combinators
- vector
- ghc-prim
- hspec
- QuickCheck
- regex-posix

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
